### ISSUE TITLE
No rollback to min/max value of byte.

### ISSUE THREAD

**Issue by kulishnik22** [zonble/brainfuck_dart#1]
Some Brainfuck programs rely on the principle that once the data at current pointer reaches -128 and you try to decrease it, it will rollback to 127. The same thing applies when you try to increase the value that is 127. It should rollback to -128.
Example of such program is the current shortest Hello World program.
Currently the shortest Hello World program in Brainfuck:
+[>>>->-[>->----<<<]>>]>.---.>+..+++.>>.<.>>---.<<<.+++.------.<-.>>+.
If you try to run it, it will be stuck in cycle.
Possible solution is to change the type of "data" list from List<int> to Uint8List

**Comment by kulishnik22** [comment]
The above workaround is not the correct way to go. You just need to change the type of data list from List<int> to Unit8List. Sorry for the mistake.

**Comment by zonble** [comment]
Fixed :)
